name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # SETUP
      - uses: actions/checkout@v2

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: .spago

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install YARN
        run: npm install -g yarn

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # yarn cache files are stored in `~/.cache/yarn` on Linux/macOS
          path: ~/.cache/yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install YARN dependencies
        run: yarn install --frozen-lockfile

      # BUILD
      - name: Build source
        run: yarn build

      # TEST
      - name: Run tests
        run: yarn test

      # COPY TO DIST
      - name: Create dist
        run: mkdir dist

      - name: Copy package.json
        run: cp package.deploy.json dist/package.json

      - name: Copy next.config.js
        run: cp next.config.js dist/next.config.js

      - name: Copy postcss.config.cjs
        run: cp postcss.config.cjs dist/postcss.config.cjs

      - name: Copy tailwind.config.cjs
        run: cp tailwind.config.cjs dist/tailwind.config.cjs

      - name: Copy output to dist
        run: cp -r --parents output dist

      - name: Copy pages to dist
        run: cp -r --parents pages dist

      - name: Copy styles to dist
        run: cp -r --parents styles dist

      # PUBLISH
      - name: Publish to demo branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: demo
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

